namespace CrewSizer.Tui;

public record HelpEntry(string Name, string[] Lines);

public static class HelpContent
{
    public static readonly List<HelpEntry> Entries =
    [
        new("calc",
        [
            "calc",
            "",
            "Lancer le calcul de marge d'engagement et",
            "afficher le rapport complet : capacite, besoin,",
            "marge par categorie (CDB, OPL, CC, PNC),",
            "verifications cumulatives, TSV max et duty.",
            "",
            "Usage :",
            "  calc",
            "",
            "Le calcul utilise la configuration courante.",
            "Modifiez les parametres avec 'set' avant de",
            "relancer 'calc' pour des scenarios what-if.",
        ]),

        new("edit",
        [
            "edit",
            "",
            "Ouvrir le formulaire de saisie.",
            "Raccourci clavier : F2",
            "",
            "Permet de modifier tous les parametres",
            "de la configuration dans un formulaire",
            "interactif.",
            "",
            "Navigation :",
            "  Fleches haut/bas  Selectionner champ",
            "  PgUp/PgDn        Section suivante",
            "  Enter             Editer le champ",
            "  Suppr             Supprimer element",
            "  F2                Valider et fermer",
            "  Esc               Annuler et fermer",
        ]),

        new("prog",
        [
            "prog",
            "",
            "Ouvrir le gestionnaire de programme.",
            "Raccourci clavier : F3",
            "",
            "Navigation hierarchique :",
            "  Semaines Types  Liste des semaines types",
            "    Enter         Voir les blocs",
            "    ←→            Changer la saison",
            "    Ins            Ajouter une semaine type",
            "    Suppr          Supprimer",
            "    C              Catalogue des vols types",
            "    Tab            Calendrier",
            "",
            "  Blocs           Table des blocs",
            "    Enter         Editer un bloc",
            "    Ins            Ajouter un bloc",
            "    Suppr          Supprimer",
            "    Esc            Retour",
            "",
            "  Bloc Edit       Edition champ par champ",
            "    ←→            Cycler selecteur (Jour/Per.)",
            "    Enter         Editer champ texte",
            "    Enter (Vols)  Ouvrir la liste des vols",
            "    Esc            Retour",
            "",
            "  Vols du bloc    Liste des vols",
            "    Enter         Editer un vol",
            "    Ins            Ajouter depuis le catalogue",
            "    M              Toggle MH (modif. horaire)",
            "    Suppr          Supprimer le vol",
            "    Esc            Retour",
            "",
            "  Vol Edit        Edition d'un vol",
            "    ↑↓            Champ suivant/precedent",
            "    Enter         Editer le champ",
            "    Esc            Retour",
            "",
            "  Catalogue       Vols types (referentiel)",
            "    Enter         Editer (popup) / Selectionner",
            "    Ins            Ajouter un vol type",
            "    Suppr          Supprimer",
            "    Esc            Retour",
            "",
            "  Calendrier      Affectation S01-S53",
            "    ←→            Changer la semaine type",
            "    Tab            Retour aux types",
        ]),

        new("show",
        [
            "show [section]",
            "",
            "Afficher la configuration courante.",
            "Sans argument : affiche toutes les sections.",
            "",
            "Sections disponibles :",
            "  effectif    Effectif CDB/OPL/CC/PNC",
            "  ftl         Limites FTL (TSV, repos)",
            "  semtypes    Semaines types et leurs blocs",
            "  calendrier  Calendrier d'affectation",
            "  programme   Programme resolu pour le mois",
            "  abat        Abattements PNT et PNC",
            "  sol         Fonctions sol PNT et PNC",
            "  cumul       Limites et compteurs cumulatifs",
            "  off         Jours OFF",
            "",
            "Exemples :",
            "  > show",
            "  > show semtypes",
            "  > show calendrier",
            "  > show programme",
        ]),

        new("set",
        [
            "set <parametre> <valeur>",
            "",
            "Modifier un parametre de la configuration.",
            "",
            "Effectif :",
            "  set cdb 14          Nombre de CDB",
            "  set opl 12          Nombre d'OPL",
            "  set cc 10           Nombre de CC",
            "  set pnc 8           Nombre de PNC",
            "",
            "Calendrier :",
            "  set cal 10 2026 BS_01       Affecter S10",
            "  set cal 10-14 2026 HS_01    Affecter plage",
            "",
            "FTL :",
            "  set tsv 10.5        TSV moyen retenu",
            "  set tsvmax 13.0     TSV max journalier",
            "  set repos 12.0      Repos minimum",
            "",
            "Periode :",
            "  set mois Mars 2026 31",
            "",
            "Jours OFF :",
            "  set off 8 2         reglementaire + accord",
            "",
            "Limites cumulatives :",
            "  set h28max 100",
            "  set h90max 280",
            "  set h12max 900",
            "  set cumul pnt 28 50   compteur entrant",
            "  set cumul pnc 90 100",
        ]),

        new("add",
        [
            "add <type> <parametres>",
            "",
            "Ajouter un element a la configuration.",
            "",
            "Semaine type :",
            "  add semtype <ref> <saison>",
            "  add semtype HS_01 Haute",
            "",
            "Bloc de vol (dans une semaine type) :",
            "  add bloc <ref> <seq> <jour> <per>",
            "       <debutDP> <finDP> <debutFDP> <finFDP>",
            "       <num-dep-arr-hdep-harr> [...]",
            "  add bloc BS_01 1 Lundi matin 06:10 11:50",
            "       06:10 11:30 201-NOU-LIF-07:00-07:40",
            "  (vol: numero-depart-arrivee-hDepart-hArrivee)",
            "",
            "Abattement :",
            "  add abat pnt <libelle> <jours>",
            "  add abat pnc <libelle> <jours>",
            "  add abat pnt Stage_pilotage 5",
            "  (remplacer espaces par _ dans le libelle)",
            "",
            "Fonction sol :",
            "  add sol pnt <nom> <nbPersonnes> <joursMois>",
            "  add sol pnc <nom> <nbPersonnes> <joursMois>",
            "  add sol pnt Instructeur 1 6",
        ]),

        new("del",
        [
            "del <type> <parametres>",
            "",
            "Supprimer un element.",
            "Utilisez 'show' pour voir les numeros.",
            "",
            "Semaine type :",
            "  del semtype BS_01    Supprimer (+ calendrier)",
            "",
            "Bloc de vol :",
            "  del bloc BS_01 3    Supprimer le 3e bloc",
            "",
            "Abattement :",
            "  del abat pnt 2      Supprimer le 2e abat PNT",
            "  del abat pnc 1      Supprimer le 1er abat PNC",
            "",
            "Fonction sol :",
            "  del sol pnt 1       Supprimer la 1ere sol PNT",
            "  del sol pnc 2       Supprimer la 2e sol PNC",
        ]),

        new("save",
        [
            "save <chemin.xml>",
            "",
            "Sauvegarder la configuration dans un fichier XML.",
            "",
            "Sans argument : sauvegarde dans le fichier",
            "courant (si deja charge depuis un fichier).",
            "",
            "Note : l'auto-save est active des qu'un",
            "fichier est associe a la configuration.",
            "",
            "Exemples :",
            "  > save config_mars.xml",
            "  > save",
        ]),

        new("load",
        [
            "load <chemin.xml>",
            "",
            "Charger une configuration depuis un fichier XML.",
            "",
            "La configuration courante est remplacee.",
            "",
            "Exemples :",
            "  > load config_mars.xml",
        ]),

        new("new",
        [
            "new",
            "",
            "Reinitialiser la configuration aux valeurs",
            "par defaut.",
            "",
            "Attention : les modifications non sauvegardees",
            "seront perdues.",
        ]),

        new("help",
        [
            "help",
            "",
            "Afficher cette aide.",
            "Raccourci clavier : F1",
            "",
            "Navigation :",
            "  Fleches haut/bas  Selectionner commande",
            "  PgUp/PgDn        Defiler le detail",
            "  Esc               Fermer l'aide",
        ]),

        new("quit",
        [
            "quit / exit",
            "",
            "Quitter l'application.",
            "Raccourcis : F10, Escape",
            "",
            "Si des modifications n'ont pas ete sauvegardees,",
            "un avertissement sera affiche.",
        ]),
    ];
}
