// <auto-generated />
using System;
using System.Collections.Generic;
using CrewSizer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrewSizer.Infrastructure.Migrations
{
    [DbContext(typeof(CrewSizerDbContext))]
    [Migration("20260228050831_AddBlocType")]
    partial class AddBlocType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrewSizer.Domain.Entities.AffectationEquipage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Activite")
                        .HasColumnType("integer")
                        .HasColumnName("activite");

                    b.Property<string>("BlocCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bloc_code");

                    b.Property<Guid>("BlocId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloc_id");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double>("HeuresVol")
                        .HasColumnType("double precision")
                        .HasColumnName("heures_vol");

                    b.Property<Guid>("MembreId")
                        .HasColumnType("uuid")
                        .HasColumnName("membre_id");

                    b.Property<double>("TempsService")
                        .HasColumnType("double precision")
                        .HasColumnName("temps_service");

                    b.HasKey("Id")
                        .HasName("p_k_affectations_equipage");

                    b.HasIndex("MembreId", "Date")
                        .HasDatabaseName("i_x_affectations_equipage_membre_id_date");

                    b.ToTable("affectations_equipage");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.BlocType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("DebutPlage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("debut_plage");

                    b.Property<double>("FdpMax")
                        .HasColumnType("double precision")
                        .HasColumnName("fdp_max");

                    b.Property<string>("FinPlage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("fin_plage");

                    b.Property<bool>("HauteSaison")
                        .HasColumnType("boolean")
                        .HasColumnName("haute_saison");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("libelle");

                    b.HasKey("Id")
                        .HasName("p_k_bloc_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_bloc_types_code");

                    b.ToTable("bloc_types");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.BlocVol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BlocTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloc_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("DebutDP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("debut_dp");

                    b.Property<string>("DebutFDP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("debut_fdp");

                    b.Property<string>("FinDP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("fin_dp");

                    b.Property<string>("FinFDP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("fin_fdp");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("jour");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("periode");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("p_k_blocs_vol");

                    b.HasIndex("BlocTypeId")
                        .HasDatabaseName("i_x_blocs_vol_bloc_type_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_blocs_vol_code");

                    b.ToTable("blocs_vol");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.CalculSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calcule_par");

                    b.Property<string>("CategorieContraignante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categorie_contraignante");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_calcul");

                    b.Property<string>("ResultatJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resultat_json");

                    b.Property<int>("Rotations")
                        .HasColumnType("integer")
                        .HasColumnName("rotations");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("StatutGlobal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut_global");

                    b.Property<double>("TauxEngagementGlobal")
                        .HasColumnType("double precision")
                        .HasColumnName("taux_engagement_global");

                    b.Property<int>("TotalBlocs")
                        .HasColumnType("integer")
                        .HasColumnName("total_blocs");

                    b.Property<double>("TotalHDV")
                        .HasColumnType("double precision")
                        .HasColumnName("total_hdv");

                    b.HasKey("Id")
                        .HasName("p_k_snapshots");

                    b.HasIndex("DateCalcul")
                        .HasDatabaseName("i_x_snapshots_date_calcul");

                    b.HasIndex("ScenarioId")
                        .HasDatabaseName("i_x_snapshots_scenario_id");

                    b.ToTable("snapshots");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("ChecksRequis")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checks_requis");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("Groupe")
                        .HasColumnType("integer")
                        .HasColumnName("groupe");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("libelle");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_competences");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_competences_code");

                    b.ToTable("competences");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.ConfigurationScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cree_par");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modification");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modifie_par");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_scenarios");

                    b.ToTable("scenarios");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.DefinitionCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvertissementNombre")
                        .HasColumnType("integer")
                        .HasColumnName("avertissement_nombre");

                    b.Property<string>("AvertissementUnite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avertissement_unite");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("FinDAnnee")
                        .HasColumnType("boolean")
                        .HasColumnName("fin_d_annee");

                    b.Property<bool>("FinDeMois")
                        .HasColumnType("boolean")
                        .HasColumnName("fin_de_mois");

                    b.Property<int>("Groupe")
                        .HasColumnType("integer")
                        .HasColumnName("groupe");

                    b.Property<bool>("Primaire")
                        .HasColumnType("boolean")
                        .HasColumnName("primaire");

                    b.Property<int>("RenouvellementNombre")
                        .HasColumnType("integer")
                        .HasColumnName("renouvellement_nombre");

                    b.Property<string>("RenouvellementUnite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("renouvellement_unite");

                    b.Property<int>("ValiditeNombre")
                        .HasColumnType("integer")
                        .HasColumnName("validite_nombre");

                    b.Property<string>("ValiditeUnite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("validite_unite");

                    b.HasKey("Id")
                        .HasName("p_k_definitions_check");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_definitions_check_code");

                    b.ToTable("definitions_check");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.DisponibiliteMembre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<string>("MembreCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("membre_code");

                    b.Property<Guid>("MembreId")
                        .HasColumnType("uuid")
                        .HasColumnName("membre_id");

                    b.Property<int>("Motif")
                        .HasColumnType("integer")
                        .HasColumnName("motif");

                    b.HasKey("Id")
                        .HasName("p_k_disponibilites_membre");

                    b.HasIndex("MembreId")
                        .HasDatabaseName("i_x_disponibilites_membre_membre_id");

                    b.ToTable("disponibilites_membre");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.HistoriqueHDV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Cumul12m")
                        .HasColumnType("double precision")
                        .HasColumnName("cumul12m");

                    b.Property<double>("Cumul28j")
                        .HasColumnType("double precision")
                        .HasColumnName("cumul28j");

                    b.Property<double>("Cumul90j")
                        .HasColumnType("double precision")
                        .HasColumnName("cumul90j");

                    b.Property<DateTime>("DateReleve")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_releve");

                    b.Property<string>("MembreCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("membre_code");

                    b.Property<Guid>("MembreId")
                        .HasColumnType("uuid")
                        .HasColumnName("membre_id");

                    b.HasKey("Id")
                        .HasName("p_k_historiques_hdv");

                    b.HasIndex("MembreId", "DateReleve")
                        .HasDatabaseName("i_x_historiques_hdv_membre_id_date_releve");

                    b.ToTable("historiques_hdv");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.MembreEquipage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.PrimitiveCollection<List<string>>("Bases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bases");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categorie");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("Contrat")
                        .HasColumnType("integer")
                        .HasColumnName("contrat");

                    b.Property<DateTime?>("DateEntree")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_entree");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricule");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.PrimitiveCollection<List<string>>("ReglesApplicables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regles_applicables");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<string>("TypeAvion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_avion");

                    b.HasKey("Id")
                        .HasName("p_k_membres_equipage");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_membres_equipage_code");

                    b.ToTable("membres_equipage");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.SemaineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference");

                    b.Property<string>("Saison")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("saison");

                    b.HasKey("Id")
                        .HasName("p_k_semaines_types");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("i_x_semaines_types_reference");

                    b.ToTable("semaines_types");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.Vol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arrivee")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("arrivee");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("depart");

                    b.Property<string>("HeureArrivee")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("heure_arrivee");

                    b.Property<string>("HeureDepart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("heure_depart");

                    b.Property<bool>("MH")
                        .HasColumnType("boolean")
                        .HasColumnName("mh");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("p_k_vols");

                    b.HasIndex("Numero")
                        .HasDatabaseName("i_x_vols_numero");

                    b.ToTable("vols");
                });

            modelBuilder.Entity("CrewSizer.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NomComplet")
                        .HasColumnType("text")
                        .HasColumnName("nom_complet");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_k_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_k_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_k_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.BlocVol", b =>
                {
                    b.HasOne("CrewSizer.Domain.Entities.BlocType", "BlocType")
                        .WithMany()
                        .HasForeignKey("BlocTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_blocs_vol_bloc_types_bloc_type_id");

                    b.OwnsMany("CrewSizer.Domain.Entities.EtapeVol", "Etapes", b1 =>
                        {
                            b1.Property<Guid>("BlocVolId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<Guid>("VolId")
                                .HasColumnType("uuid");

                            b1.HasKey("BlocVolId", "__synthesizedOrdinal");

                            b1.ToTable("blocs_vol");

                            b1
                                .ToJson("etapes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BlocVolId");
                        });

                    b.Navigation("BlocType");

                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.CalculSnapshot", b =>
                {
                    b.HasOne("CrewSizer.Domain.Entities.ConfigurationScenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_snapshots__scenarios_scenario_id");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.ConfigurationScenario", b =>
                {
                    b.OwnsMany("CrewSizer.Domain.Entities.AffectationSemaine", "Calendrier", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Annee")
                                .HasColumnType("integer");

                            b1.Property<int>("Semaine")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SemaineTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SemaineTypeRef")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("calendrier")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsMany("CrewSizer.Domain.ValueObjects.Abattement", "AbattementsPNC", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("JoursPersonnel")
                                .HasColumnType("integer");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("abattements_pnc")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsMany("CrewSizer.Domain.ValueObjects.Abattement", "AbattementsPNT", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("JoursPersonnel")
                                .HasColumnType("integer");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("abattements_pnt")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsMany("CrewSizer.Domain.ValueObjects.FonctionSol", "FonctionsSolPNC", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("JoursSolMois")
                                .HasColumnType("integer");

                            b1.Property<int>("NbPersonnes")
                                .HasColumnType("integer");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("fonctions_sol_pnc")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsMany("CrewSizer.Domain.ValueObjects.FonctionSol", "FonctionsSolPNT", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("JoursSolMois")
                                .HasColumnType("integer");

                            b1.Property<int>("NbPersonnes")
                                .HasColumnType("integer");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("fonctions_sol_pnt")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.Effectif", "Effectif", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Cc")
                                .HasColumnType("integer")
                                .HasColumnName("effectif_cc");

                            b1.Property<int>("Cdb")
                                .HasColumnType("integer")
                                .HasColumnName("effectif_cdb");

                            b1.Property<int>("Opl")
                                .HasColumnType("integer")
                                .HasColumnName("effectif_opl");

                            b1.Property<int>("Pnc")
                                .HasColumnType("integer")
                                .HasColumnName("effectif_pnc");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsMany("CrewSizer.Domain.ValueObjects.EntreeTsvMax", "TableTsvMax", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("DebutBande")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FinBande")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MaxParEtapes")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ConfigurationScenarioId", "__synthesizedOrdinal");

                            b1.ToTable("scenarios");

                            b1
                                .ToJson("table_tsv_max")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.JoursOff", "JoursOff", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AccordEntreprise")
                                .HasColumnType("integer")
                                .HasColumnName("jours_off_accord_entreprise");

                            b1.Property<int>("Reglementaire")
                                .HasColumnType("integer")
                                .HasColumnName("jours_off_reglementaire");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.LimitesCumulatives", "LimitesCumulatives", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<double>("H12Max")
                                .HasColumnType("double precision")
                                .HasColumnName("cumul_h12_max");

                            b1.Property<double>("H28Max")
                                .HasColumnType("double precision")
                                .HasColumnName("cumul_h28_max");

                            b1.Property<double>("H90Max")
                                .HasColumnType("double precision")
                                .HasColumnName("cumul_h90_max");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");

                            b1.OwnsOne("CrewSizer.Domain.ValueObjects.CumulEntrant", "CumulPNC", b2 =>
                                {
                                    b2.Property<Guid>("LimitesCumulativesConfigurationScenarioId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Cumul12Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnc_12_entrant");

                                    b2.Property<double>("Cumul28Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnc_28_entrant");

                                    b2.Property<double>("Cumul90Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnc_90_entrant");

                                    b2.HasKey("LimitesCumulativesConfigurationScenarioId");

                                    b2.ToTable("scenarios");

                                    b2.WithOwner()
                                        .HasForeignKey("LimitesCumulativesConfigurationScenarioId");
                                });

                            b1.OwnsOne("CrewSizer.Domain.ValueObjects.CumulEntrant", "CumulPNT", b2 =>
                                {
                                    b2.Property<Guid>("LimitesCumulativesConfigurationScenarioId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Cumul12Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnt_12_entrant");

                                    b2.Property<double>("Cumul28Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnt_28_entrant");

                                    b2.Property<double>("Cumul90Entrant")
                                        .HasColumnType("double precision")
                                        .HasColumnName("cumul_pnt_90_entrant");

                                    b2.HasKey("LimitesCumulativesConfigurationScenarioId");

                                    b2.ToTable("scenarios");

                                    b2.WithOwner()
                                        .HasForeignKey("LimitesCumulativesConfigurationScenarioId");
                                });

                            b1.Navigation("CumulPNC")
                                .IsRequired();

                            b1.Navigation("CumulPNT")
                                .IsRequired();
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.LimitesFTL", "LimitesFTL", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<double>("ReposMinimum")
                                .HasColumnType("double precision")
                                .HasColumnName("ftl_repos_minimum");

                            b1.Property<double>("TsvMaxJournalier")
                                .HasColumnType("double precision")
                                .HasColumnName("ftl_tsv_max_journalier");

                            b1.Property<double>("TsvMoyenRetenu")
                                .HasColumnType("double precision")
                                .HasColumnName("ftl_tsv_moyen_retenu");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.LimitesTempsService", "LimitesTempsService", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Max14j")
                                .HasColumnType("double precision")
                                .HasColumnName("ts_max_14j");

                            b1.Property<double>("Max28j")
                                .HasColumnType("double precision")
                                .HasColumnName("ts_max_28j");

                            b1.Property<double>("Max7j")
                                .HasColumnType("double precision")
                                .HasColumnName("ts_max_7j");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.OwnsOne("CrewSizer.Domain.ValueObjects.Periode", "Periode", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationScenarioId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DateDebut")
                                .HasColumnType("date")
                                .HasColumnName("periode_date_debut");

                            b1.Property<DateOnly>("DateFin")
                                .HasColumnType("date")
                                .HasColumnName("periode_date_fin");

                            b1.HasKey("ConfigurationScenarioId");

                            b1.ToTable("scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationScenarioId");
                        });

                    b.Navigation("AbattementsPNC");

                    b.Navigation("AbattementsPNT");

                    b.Navigation("Calendrier");

                    b.Navigation("Effectif")
                        .IsRequired();

                    b.Navigation("FonctionsSolPNC");

                    b.Navigation("FonctionsSolPNT");

                    b.Navigation("JoursOff")
                        .IsRequired();

                    b.Navigation("LimitesCumulatives")
                        .IsRequired();

                    b.Navigation("LimitesFTL")
                        .IsRequired();

                    b.Navigation("LimitesTempsService")
                        .IsRequired();

                    b.Navigation("Periode")
                        .IsRequired();

                    b.Navigation("TableTsvMax");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.MembreEquipage", b =>
                {
                    b.OwnsMany("CrewSizer.Domain.Entities.StatutQualification", "Qualifications", b1 =>
                        {
                            b1.Property<Guid>("MembreEquipageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("CodeCheck")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DateExpiration")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Statut")
                                .HasColumnType("integer");

                            b1.HasKey("MembreEquipageId", "__synthesizedOrdinal");

                            b1.ToTable("membres_equipage");

                            b1
                                .ToJson("qualifications")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MembreEquipageId");
                        });

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("CrewSizer.Domain.Entities.SemaineType", b =>
                {
                    b.OwnsMany("CrewSizer.Domain.Entities.BlocPlacement", "Placements", b1 =>
                        {
                            b1.Property<Guid>("SemaineTypeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("BlocId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Jour")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.HasKey("SemaineTypeId", "__synthesizedOrdinal");

                            b1.ToTable("semaines_types");

                            b1
                                .ToJson("placements")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SemaineTypeId");
                        });

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CrewSizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CrewSizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("CrewSizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CrewSizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
